// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3l503KtkYcBNY4FLcs_v3Zpel1fH0nrw',
    appId: '1:168077709490:web:aa56b984091cac81f9f9ab',
    messagingSenderId: '168077709490',
    projectId: 'organic-plants',
    authDomain: 'organic-plants.firebaseapp.com',
    storageBucket: 'organic-plants.firebasestorage.app',
    measurementId: 'G-BQXGWQVLVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKVEiX_iUcE9qklJLMgW8Oir5E96RXvis',
    appId: '1:168077709490:android:deb5bc3ec48c77f6f9f9ab',
    messagingSenderId: '168077709490',
    projectId: 'organic-plants',
    storageBucket: 'organic-plants.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNW2h1jFl_-bMkDFTs-bzQ1xk1kjyiJJ8',
    appId: '1:168077709490:ios:147a5c5cc5f2277cf9f9ab',
    messagingSenderId: '168077709490',
    projectId: 'organic-plants',
    storageBucket: 'organic-plants.firebasestorage.app',
    androidClientId: '168077709490-tjhfp6mojdkp6e63ol7k44pb8dd7ueci.apps.googleusercontent.com',
    iosClientId: '168077709490-ed66t8t3c9v3chapevoh3v2m1gbl99to.apps.googleusercontent.com',
    iosBundleId: 'com.example.organicplants',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNW2h1jFl_-bMkDFTs-bzQ1xk1kjyiJJ8',
    appId: '1:168077709490:ios:147a5c5cc5f2277cf9f9ab',
    messagingSenderId: '168077709490',
    projectId: 'organic-plants',
    storageBucket: 'organic-plants.firebasestorage.app',
    androidClientId: '168077709490-tjhfp6mojdkp6e63ol7k44pb8dd7ueci.apps.googleusercontent.com',
    iosClientId: '168077709490-ed66t8t3c9v3chapevoh3v2m1gbl99to.apps.googleusercontent.com',
    iosBundleId: 'com.example.organicplants',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3l503KtkYcBNY4FLcs_v3Zpel1fH0nrw',
    appId: '1:168077709490:web:f5c046ffd9e32228f9f9ab',
    messagingSenderId: '168077709490',
    projectId: 'organic-plants',
    authDomain: 'organic-plants.firebaseapp.com',
    storageBucket: 'organic-plants.firebasestorage.app',
    measurementId: 'G-6PBXC2EK1X',
  );
}
